name: release-gem

on:
  push:
    branches:
      - main
    paths:
      - lib/rbs/trace/version.rb
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: write
      id-token: write

    environment: release

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - uses: rubygems/release-gem@v1
