name: Test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install RBS files
      if: ${{ matrix.ruby == '3.3' }}
      run: bundle exec rbs collection install --frozen

    - name: Run the default task
      run: bundle exec rake

    - name: Check RBS files are committed
      if: ${{ matrix.ruby == '3.3' }}
      run: git diff --exit-code sig
